### ISSUE TITLE
Reduce file size of PDF report

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfcommercial#2]
We can likely reduce the png figure resolution and we can also pass the pngs through optipng to further reduce file size without any visual penalty. We should be able to get it down to under 100 mb. The original synopsis report is > 200 pages of figures and can be a bit over 100 mb with these 2 tricks. @leah-walker 

https://github.com/pbs-assess/gfsynopsis/blob/fef0d71c4f6be41131a72b69e70306155eae192d/report/make.R#L397
https://github.com/pbs-assess/gfsynopsis/blob/master/R/make-pages.R#L1507
https://github.com/pbs-assess/gfsynopsis/blob/fef0d71c4f6be41131a72b69e70306155eae192d/report/make.R#L646-L649

We'll have to work out how to use optipng on a DFO Windows machine, or I can run optipng for you.

**Comment by leah-walker** [comment]
png file size reduced to 200 dpi and optimized through optipng
